version: '3'

services:
  app0:
    build:
      context: ./app0
    container_name: app0
    ports:
      - "8001:8000"
    networks:
      - app-network

  app1:
    build:
      context: ./app1
    container_name: app1
    ports:
      - "8002:8000"
    networks:
      - app-network

  app2:
    build:
      context: ./app2
    container_name: app2
    ports:
      - "8003:8000"
    networks:
      - app-network

  app3:
    build:
      context: ./app3
    container_name: app3
    ports:
      - "8004:8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app0
      - app1
      - app2
      - app3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
