version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: ./app1
    ports:
      - "8001:8000"

  app2:
    build: ./app2
    ports:
      - "8002:8000"

  app3:
    build: ./app3
    ports:
      - "8003:8000"
